#!/bin/sh
# script for conversion of filetypes.conf into filetypes.h
# (called by Makefile before compilation)
# (2019-6-18 // HB9KNS)
inpt=filetypes.conf
outp=${inpt%.*}.h
if test -r $inpt
then
 cat <<EOH >$outp
/* $outp autogenerated on `date -u` by $0 */

#define FILETYPES \\
EOH
# slurp $inpt and get gopher type and list of extensions
 cat $inpt | { while read gtype exts
 do if ! test "$gtype" = "" -o "$gtype" = "#"
# process extensions, removing trailing SPC,
# prepending '"' and appending '","gophertype",' to each,
# and prepending TAB and appending ' \'
 then echo $exts | sed -e "s/\([^ ][^ ]*\) */\"\1\",\"$gtype\",/g;s/^/	/;s/\$/ \\\\/" >>$outp
 fi
 done
 }
 cat <<EOF >>$outp
	NULL, NULL
EOF
else
 echo "Warning: no readable file type config file '$inpt' found, please check!"
 exit 1
fi
