.\" Manpage for gophernicus.
.TH man 1 "26 Oct 2019" "3.0.1" "gophernicus man page"
.SH NAME
gophernicus \- a modern, full-featured and secure gopher daemon
.SH SYNOPSIS
.B gophernicus
[options]
.SH DESCRIPTION
.B gophernicus
is a daemon that serves the gopher protocol. It serves almost fully
compliant RFC 1436, with a few very small changes to make it more modern.
gophernicus has many useful features, including userdirs, executable gophermaps,
virtual hosting as well as RFC supports it, unveil/pledge support on OpenBSD and
much more. It is fully FOSS, and licensed under the BSD 2-Clause license.
.SH OPTIONS
  -h hostname   Change server hostname (FQDN)      [$HOSTNAME]
  -p port       Change server port                 [70]
  -T port       Change TLS/SSL port                [0 = disabled]
  -r root       Change gopher root                 [/var/gopher]
  -t type       Change default gopher filetype     [0]
  -g mapfile    Change gophermap file              [gophermap]
  -a tagfile    Change gophertag file              [gophertag]
  -c cgidir     Change CGI script directory        [/cgi-bin/]
  -u userdir    Change users personal gopherspace  [public_gopher]
  -l logfile    Log to Apache-compatible combined format logfile

  -w width      Change default page width          [76]
  -o charset    Change default output charset      [UTF-8]

  -s seconds    Session timeout in seconds         [1800]
  -i hits       Maximum hits until throttling      [4096]
  -k kbytes     Maximum transfer until throttling  [4194304]

  -f filterdir  Specify directory for output filters
  -e ext=type   Map file extension to gopher filetype
  -R old=new    Rewrite the beginning of a selector

  -D text|file  Set or load server description for caps.txt
  -L text|file  Set or load server location for caps.txt
  -A admin      Set admin email for caps.txt

  -U paths      Specify a colon-separated list of extra unveil(2) paths
                (OpenBSD only).

  -nv           Disable virtual hosting
  -nl           Disable parent directory links
  -nh           Disable menu header (title)
  -nf           Disable menu footer
  -nd           Disable dates and filesizes in menus
  -nc           Disable file content detection
  -no           Disable charset conversion for output
  -nq           Disable HTTP-style query strings (?query)
  -ns           Disable logging to syslog
  -na           Disable autogenerated caps.txt
  -nt           Disable /server-status
  -nm           Disable shared memory use (for debugging)
  -nr           Disable root user checking (for debugging)
  -np           Disable HAproxy proxy protocol
  -nx           Disable execution of gophermaps and scripts
  -nu           Disable personal gopherspaces
  -nH           Disable HTTP response to HTTP GET/POST requests.

  -d            Debug output in syslog and /server-status
  -v            Display version number and build date
  -b            Display the BSD license
  -?            Display this help

(Note: default options may have been changed through gophernicus.env file at compile time.)
.SH AUTHOR
fosslinux, hb9kns and others; <gophernicus at gophernicus dot org>
.SH REPORTING BUGS
Please report bugs on our GitHub page:
https://github.com/gophernicus/gophernicus.
.SH COPYRIGHT
Copyright (c) Kim Holviala 2009-2018
Copyright (c) Gophernicus Developers 2019

Licensed to you under the terms of the BSD 2-Clause license, please see LICENSE
for the full terms of the license.
