#!/bin/sh

##
## Generate Gophernicus version/build number
##

MAJOR=2
MINOR=99

if which git >/dev/null && test -d .git; then
	printf "${MAJOR}."
	git log | grep -c "^commit"
else
	echo ${MAJOR}.${MINOR}
fi

