#!/usr/bin/env sh
printf "updating system...\\n"
zypper -n refresh > /dev/null
zypper -n update > /dev/null
printf "installing dependencies...\\n"
zypper -n install --type pattern devel_C_C++ > /dev/null
zypper -n install --type pattern devel_basis > /dev/null
zypper -n install git which > /dev/null
